## Basic Configuration
baseurl = "http://jdaytn.com/"
languageCode = "en"

theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = ""
# googleAnalytics = ""
# enableRobotsTXT = true

## Site Settings
[params]
    author = "Jonathan Dayton"
    title = "Data Science, et al."
    description = "Jonathan Dayton. Data Science, et al."
    authorimage = "/img/jonathan.jpg"
    dateformat = "January 01, 2006"
    highlightjs = true
    highlightjsstyle = "ir-black"

## Social Accounts
[params.social]
    github = "jdayton3"
    linkedin = "jdayton3"
    twitter = "JDayton23"
    stackoverflow = "6481442"
    email = "jonathandayton23@gmail.com"

## Main Menu
[[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "Blog"
    weight = 2
    identifier = "blog"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 3
    url = "/about/"
